### ISSUE TITLE
Check that the library works with the wasm32-unknown-unknown target in CI

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#120]
I think `cargo test --all` tests all targets, so we would only need to `rustup target add wasm32-unknown-unknown` beforehand. Otherwise we can `cargo test --all --target=wasm32-unknown-unknown`.

**Comment by maxymshg** [comment]
Hi, I'm looking into list of targets using `rustup target list` command and `wasm32-unknown-unknown` is there. Does it mean that `cargo test --all` already will test over this target or I miss something?

**Comment by maxymshg** [comment]
Also, I looked over this [hello wasm guide](https://www.hellorust.com/setup/wasm-target/) and tried to run tests for nightly and got next:
```shell
error[E0046]: not all trait items implemented, missing: `encode`
    --> C:\Users\maxim\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-serialize-0.3.24\src\serialize.rs:1358:1
     |
853  |     fn encode<S: Encoder>(&self, s: &mut S) -> Result<(), S::Error>;
     |     ---------------------------------------------------------------- `encode` from trait
...
1358 | impl Encodable for path::Path {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `encode` in implementation

error[E0046]: not all trait items implemented, missing: `decode`
    --> C:\Users\maxim\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-serialize-0.3.24\src\serialize.rs:1382:1
     |
904  |     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
     |     ----------------------------------------------------------- `decode` from trait
...
1382 | impl Decodable for path::PathBuf {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `decode` in implementation

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0046`.
error: Could not compile `rustc-serialize`.
````

Is it ok for this PR an update `.travis.yml` and add lines that will add this target for nightly builds?

**Comment by tomhoule** [comment]
Thanks for giving this a try! Yes it may be hard - maybe not everything compiles cleanly there yet (that's also why I think it's useful to have it in CI). Feel free to change the `.travis.yml` - I think it's going to be necessary.

For `cargo test --all` I have doubts, I may have misread. Apparently it's `--all-targets` but I've never seen that behaviour locally (and I have multiple targets installed) so it's easier to go with the explicit `--target=wasm32-unknown-unknown` instead, in my opinion.
