### ISSUE TITLE
Only include the selected query as a string in generated modules

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#130]
To be specified further.

**Comment by h-michael** [comment]
@tomhoule  How is the specification like this?
```
query SelectName {
  person { name }
}

query SelectAge {
  person { age }
}

query SelectBirthday {
  person { birthday }
}
```

```
#[derive(GraphQLQuery)]
#[graphql(
  query_path = "..",
  schema_path = "...",
  operation_name = "SelectAge,SelectName"
)]
struct Person;
```

**Comment by ilovelll** [comment]
any update about this feature?

**Comment by tomhoule** [comment]
I don't have a lot of time to work on this project at the moment unfortunately, and this is not the highest priority, so it's unlikely to land soon unless someone else works on it. It could be bundled up with the query minification feature.

**Comment by tomhoule** [comment]
There are other issues for query minification - closing this one for inactivity.
