### ISSUE TITLE
Codegen error: cannot find type `Time` in module `super`

### ISSUE THREAD

**Issue by afternoon** [graphql-rust/graphql-client#155]
I get the following error when building my project. I have a huge schema (84MB), which sadly I can't share. I'm not sure where the issue lies. How could I debug this further?

```
error[E0412]: cannot find type `Time` in module `super`
  --> src/main.rs:10:10
   |
10 | #[derive(GraphQLQuery)]
   |          ^^^^^^^^^^^^ not found in `super`
```

**Comment by tomhoule** [comment]
The message looks like `Time` is a custom scalar. The custom scalar has to be defined in the scope where the struct under derive is located. So if `Time` is serialized as a string for example, a simple `type Time = String;` next to the query struct should work.

We should document this better - I'll add it to the milestone for the coming release.

**Comment by afternoon** [comment]
Yep, that fixed it!
