### ISSUE TITLE
Write a better wasm example

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#156]
Now that the web-sys crate and wasm-pack are ready, we can make the existing example much fancier or write a completely new one. The code will also be a lot cleaner with those.

**Comment by sgrove** [comment]
Any chance you can share any progress on this?

**Comment by tomhoule** [comment]
I will probably rewrite the example as part of this PR: https://github.com/graphql-rust/graphql-client/pull/174 - sadly I haven't had any time to work on it in the past few weeks but the code works. We basically "just" need better error handling, more tests, more docs and a good example before it is published as a new crate.

**Comment by tomhoule** [comment]
The web example has been rewritten - I will try to make it even better with time, as the wasm ecosystem evolves.
