### ISSUE TITLE
Run prettier on graphql and json files in CI

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#157]
So we don't have formatting problems.

**Comment by maxymshg** [comment]
Hi, I want help but don't know from where to start on this issue. I worked with prettier before on node.js projects. Could you guide me?

**Comment by tomhoule** [comment]
Sorry, I should have specified more :)

So the way I did it on other projects is to run prettier like this:

```
prettier --write './**/*.json' './**/*.graphql'
```

Since the `--write` flag is provided, it will modify files in-place. We then just fail if thee is any diff with the committed code:

```
git diff --exit-code
```

We are also going to need a .prettierrc (document in the prettier docs) to ignore the `target` directories.

**Comment by maxymshg** [comment]
Few more questions. Should it be a part of TravisCI job or it could be a pre-commit hook? And, as far as I understand it's related to examples, right?

**Comment by tomhoule** [comment]
It should be an additional step in Travis (in a [before_script](https://docs.travis-ci.com/user/customizing-the-build/#the-build-lifecycle)). We have a lot of .json and .graphql files, indeed mostly in the tests and examples.

I don't know if the travis setup for Rust has node installed, that could be a problem (since we need it to install and run prettier).

**Comment by tomhoule** [comment]
No problem, sorry for the delay in merging it - the past weeks have been a bit crazy for me :)

**Comment by tomhoule** [comment]
And thanks again for the PR!
