### ISSUE TITLE
Problem with Rust 2018 Edition (attribute `serde` is currently unknown)

### ISSUE THREAD

**Issue by aergonaut** [graphql-rust/graphql-client#176]
I'm trying to use this crate in my Rust 2018 Edition project and I'm running into an issue that's preventing my code from compiling.

The error message I get from `cargo build` is:

```
error[E0658]: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
 --> src/commands.rs:9:10
  |
9 | #[derive(GraphQLQuery)]
  |          ^^^^^^^^^^^^
  |
  = help: add #![feature(custom_attribute)] to the crate attributes to enable
```

My code looks roughly like this:

```rust
use failure::err_msg;
use failure::Error;
use graphql_client::GraphQLQuery;
use log::info;
use serde_derive::{Deserialize, Serialize};

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "github_schema.json",
    query_path = "src/graphql/pull_request_query.graphql"
)]
struct PullRequestQuery;
```

I tried adding `#[derive(Deserialize, Serialize)]` to the `PullRequestQuery` struct, but that didn't seem to change anything.

I'm not sure how else to debug this or how else to search for info about this. I noticed the examples are all written in Rust 2015 Edition, so I'm wondering if the crate isn't compatible with Rust 2018 Edition?

**Comment by aergonaut** [comment]
Confirmed that it's an issue with the Rust 2018 Edition way of importing macros.

If I add the following to my code, the error goes away:

```rust
#[macro_use]
extern crate serde_derive;
```

According to the Edition Guide, `extern crate` is no longer needed and importing procedural macros is done with normal `use` statements: https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html#procedural-macros

I'm not sure if this is something that needs to be handled by this crate, by serde, or by rustc itself.

**Comment by tomhoule** [comment]
I have had the same problem and fixed it the same way so far. One way that could work with both editions would be adding `use serde_derive::*` to all generated modules. On 2015 it should do nothing, and in 2018 it imports the derive. I will try to do this when I find the time but if anyone wants to tackle this first feel free to do so :)
