### ISSUE TITLE
CLI and build script codegen: where should we generate code?

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#182]
Currently we generate code for all queries into one module. There are however other options that may be clearer for users, in my opinion:

- For one query document (.graphql file) with multiple queries, generate one file with one module per query (then we don't need to do things like changing the names of the `ResponseData` and `Variables` structs like we currently do).
- For one query document with multiple queries, generate one file per query (we don't need a `mod` block in that case). The potential downside is that there is more potential for overwriting a file in that case.

So I would lean more for option one. I can elaborate.

It would be great to have as many opinions as possible on this :)

**Comment by mattferrin** [comment]
I've been too locked into the TypeScript world to have a valid opinion, but it seems intuitive that each .graphql file would map to a corresponding Rust file.

**Comment by tomhoule** [comment]
This issue was addressed by https://github.com/graphql-rust/graphql-client/pull/229 - I think there are more details in the Changelog too.
