### ISSUE TITLE
Codegen for server from client

### ISSUE THREAD

**Issue by mattferrin** [graphql-rust/graphql-client#189]
My intent is to make a premature feature request in hopes that your mind will be open to it occurring in the Rust ecosystem.

In my (TypeScript) clients I (mostly) have only one query field per database entity type, a GraphQL connection per each. Most my work is only to insure that the server secures those powerful query fields.

A portion of that effort is to make sure every unique subset of a field's query arguments is statically defined on the client and whitelisted on the server. Unfortunately, the server validation in my project only occurs at runtime, mostly without the aid of static type checking.

Will it be possible to generate code from client defined queries to aid in sever-side work?

Possible benefits:

Exhaustive enum matching on requests at server to enforce concerns per query field per unique subset of arguments.

Detecting the result of deprecations proactively during server development.

No whitelisting of fields not in use.

Enforce exhaustive security handling of fields in use under a given context.

GraphiQL-like tool or plugin that displays whitlisted arguments and fields.

**Comment by tomhoule** [comment]
Thanks for the suggestion! I am not sure I completely understand how this would work, and it seems like some of it would belong on the server side. I am definitely super interested in making what we generate more flexible and extensible for this purpose and others (testing, etc.), so let's keep this issue around for discussion.

**Comment by mattferrin** [comment]
Thanks for politely considering my thoughts and keeping the issue open. I've been stuck in TypeScript and not in Rust much. Having said that, I now believe in defining roles and permissions through schema directives, meaning I believe I was taking the entirely wrong approach when I opened this 6 months ago.

**Comment by tomhoule** [comment]
No problem :) Please feel free to open new issues if you have ideas for improvements! I just closed this to keep the issue tracker tidy, because there was no progress in a long time.
