### ISSUE TITLE
generate wrong fragment with union type

### ISSUE THREAD

**Issue by h-michael** [graphql-rust/graphql-client#192]
If I run `graphql-client query.graphql schema.graphql query.rs` with this [files](https://gist.github.com/h-michael/062cfced0a019741e9fc20ab3a168fbc), I got wrong fragment definition.
`custom_actor` is blank struct.

**Comment by tomhoule** [comment]
This has to be investigated, thanks for the report.

**Comment by tomhoule** [comment]
I can't reproduce the bug, I thought it was because the fragment has a snake case name but it seems to work: https://github.com/graphql-rust/graphql-client/pull/206

I'll try to think of other potential causes for the bug. Do you have an idea on what could be causing the problem?

**Comment by h-michael** [comment]
@tomhoule 
Thank you for your investigating.
I think that the case of fragment including union type might be reproduced.

**Comment by tomhoule** [comment]
I missed that part, I'll try to write a test case asap.

**Comment by tomhoule** [comment]
WIP PR to reproduce the problem: https://github.com/graphql-rust/graphql-client/pull/207

**Comment by tomhoule** [comment]
The source of the bug is found locally, it shouldn't take too long to fix it. I wrote a bunch of docs in graphql_client_codegen while investigating this, it's a bit obscure in places.

**Comment by tomhoule** [comment]
The PR is here: https://github.com/graphql-rust/graphql-client/pull/207

I refactored a few things quite heavily. This also changes how fragments on interfaces work. We can't release it without documenting the changes, and it will be a breaking release.
