### ISSUE TITLE
Platform-specific client crates organization

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#201]
We currently have the problem that the right way to use graphql_client on the web is to use the graphql_client_web crate. Should we use the graphql_client crate everywhere, but with different features for different platforms instead? The upside is that we would only have one crate exposed to users of the library, the rest being implementation details.

If we decide to do that, since the platform-specific client depend on types in graphql-client, we would have to make it a façade crate and define the common types in a `graphql-client-core` crate.

**Comment by theduke** [comment]
Why not have different features in the main graphql-client crate like `client-web` and `client` (for regular server)?

The feature dance to get the dependencies might be a bit challenging but achievable.

**Comment by tomhoule** [comment]
As of 0.8.0, graphql_client_web is deprecated, the browser client now lives in the main crate (`web` module) under a feature. We will follow the same pattern with the clients for other environments.
