### ISSUE TITLE
Add support for recursive types

### ISSUE THREAD

**Issue by theduke** [graphql-rust/graphql-client#208]
Currently, the code generation doesn't allow for recursive types and compilation will fail with an error.

Eg:

```
type Node {
  left: Node
  right: Node
}
```

This should be supportable relatively easily by detecting the recursion  and boxing the type where necessary (serde supports Box<> ed types).

**Comment by theduke** [comment]
If @tomhoule or @h-michael  could take a look here I'd be very thankful.
I need this soon-ish and don't have time to dive into the code right now.

**Comment by tomhoule** [comment]
This can only happen with a fragment selecting itself, I think. It should be very easy to write a test case and fix this, thanks for the report, I'll try to work on it asap (if anyone else wants to it's great as well, of course).

**Comment by theduke** [comment]
In my case it wasn't a fragment, but a input object that contains a recursion.

**Comment by tomhoule** [comment]
I just opened a PR to fix this: https://github.com/graphql-rust/graphql-client/pull/209

The branch is rebased on the fragments on unions bug fix branch (it has a PR too) because I did some considerable yak shaving on that one. I will try to merge it asap but you can probably use the branch in the meantime.

**Comment by tomhoule** [comment]
Let's keep this issue around since we have to check recursive fragments work as well.

**Comment by tomhoule** [comment]
Here's the PR for recursive fragments support: https://github.com/graphql-rust/graphql-client/pull/211

**Comment by theduke** [comment]
@tomhoule  if it helps I can add a failing test to your PR.

**Comment by tomhoule** [comment]
Mmh weird, recursive input objects should already be possible on master. If you can provide an example it would be very helpful. I haven't had time to work much on it but I have an idea on how to implement the boxing for recursive fragments (won't be optimal in the sense of minimal boxing but it will make them work, at least).

**Comment by tomhoule** [comment]
There is progress on the fragments PR - it does too much boxing at the moment. There are indeed cases where recursive input types fail to compile at the moment, but I have a good idea on how to address this. I'll try to find the time soon.

**Comment by tomhoule** [comment]
The PR is merged. Let's make a bug release (0.6.1).

**Comment by theduke** [comment]
@tomhoule can confirm that this works now, cheers.
