### ISSUE TITLE
CLI generate broken

### ISSUE THREAD

**Issue by theduke** [graphql-rust/graphql-client#220]
Currently, the `graphql-client generate` command is broken for multiple queries:

it produces a `pub const QUERY = ""; pub const OPERATION_NAME = "..";` for each query inside the same module, causing name conflicts.

**Comment by h-michael** [comment]
I'll fix it later.

**Comment by theduke** [comment]
@h-michael will you have time to do it?
Otherwise I'll take a stab at it.

**Comment by h-michael** [comment]
@theduke Sorry for my late replying.
I do not have enough time until next weekend.
So go ahead, if you could :)

**Comment by tomhoule** [comment]
Heads up: #223 cleans up some of this code (without changing the behaviour), so I would advise rebasing on it if someone started working on this issue.

**Comment by tomhoule** [comment]
This is fixed in 0.7.0.
