### ISSUE TITLE
Allow additional headers in graphql-client-cli

### ISSUE THREAD

**Issue by martimatix** [graphql-rust/graphql-client#234]
Presently, I'm working with [hasura](https://hasura.io/) and out of the box, in order to get the schema from the graphql endpoint, a `x-hasura-admin-secret` or `x-hasura-access-key` needs to be provided.

If the graphql-client-cli had a way of adding headers in addition to `authorization`, this would solve that problem.

**Comment by tomhoule** [comment]
Yes it's something we should support. I don't know what the best UX would be. Something like `--headers x-hasura-access-key:pikachu,x-hasura-admin-key:raichu` or `--header x-hasura-access-key:pikachu --header x-hasura-admin-key:raichu` (if possible, but I think it should be) maybe.

**Comment by travismiller** [comment]
@tomhoule I expect `--header 'X-A:v' --header 'X-B:v' --header 'X-C:v'` should be possible since [structopt](https://docs.rs/structopt/0.2.15/structopt/) supports `Vec<T: FromStr>` as a field. I can try and submit a PR soon if you like!

**Comment by tomhoule** [comment]
Absolutely do feel free to open a PR - I hope I can get to it soon otherwise but there are a lot of other issues and I am really short on time for open source at the moment :)

**Comment by travismiller** [comment]
@tomhoule PR submitted!

**Comment by tomhoule** [comment]
This has been implemented by @travismiller , thanks again :)
