### ISSUE TITLE
Force specifying a module for custom scalars

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#245]
One of the usability issues with the library is that we can't provide good errors for custom scalars (either the types are visible from the generated code, or they're not). In the presence of custom scalars in generated code, we could force the user of the library to specify a module to import the custom scalar types from, as a `derive` attribute.

Feedback on this would be appreciated before me or someone else implements it :)

**Comment by miterst** [comment]
@tomhoule would be very useful to have this option available. Is someone already working on it?

Maybe something like `custom_scalar_provider=....` where one can provide the path to the module that implements the necessary scalars or fallback to `super::..` if not present.

If help is sill needed me and some of my colleagues can give you a hand with this.

**Comment by tomhoule** [comment]
Nobody is actively working on this crate at the moment (I don't have time). I would be able to review and merge PRs, however.
