### ISSUE TITLE
Variables should impl Debug

### ISSUE THREAD

**Issue by MikailBag** [graphql-rust/graphql-client#248]
I think `dbg!(&vars)` is very useful for debugging purposes.
Perhaps it should be introduced as variables_derives param on `graphql` procmacro?

**Comment by tomhoule** [comment]
Yep, I think there's an issue for it. It's a feature we want, it wouldn't be too hard to implement, but it's time I sadly don't have at the moment :/ I'd be happy to mentor and/or review pull requests.

**Comment by MikailBag** [comment]
OK, I started PR.
Waiting for feedback.

**Comment by mathstuf** [comment]
Duplicate of #249.

**Comment by mathstuf** [comment]
#285 has landed and should make this possible.
