### ISSUE TITLE
Code gen: Redefinitions

### ISSUE THREAD

**Issue by davidgraeff** [graphql-rust/graphql-client#255]
I'm having issues with the code generation part. See the following example:

`common.graphql` Query file:
```graphql
query ping_query {ping}
```
`schema.graphql` Schema file:
```graphql
type Query {
  """Returns the literal string 'pong'."""
  ping: String!
}
```

Generated Rust code:
```rust
pub struct ping_query;
pub mod ping_query {
    #![allow(dead_code)]
    pub const OPERATION_NAME: &'static str = "ping_query";
    pub const QUERY: &'static str = "query ping_query {ping}";
    use serde::{Deserialize, Serialize};
    #[allow(dead_code)]
    type Boolean = bool;
    #[allow(dead_code)]
    type Float = f64;
    #[allow(dead_code)]
    type Int = i64;
    #[allow(dead_code)]
    type ID = String;
    #[derive(PartialEq, Serialize)]
    pub struct Variables;
    #[derive(Deserialize, PartialEq, Serialize)]
    pub struct ResponseData {
        #[doc = "Returns the literal string 'pong'.\n"]
        pub ping: String,
    }
}
impl graphql_client::GraphQLQuery for ping_query {
    type Variables = ping_query::Variables;
    type ResponseData = ping_query::ResponseData;
    fn build_query(variables: Self::Variables) -> ::graphql_client::QueryBody<Self::Variables> {
        graphql_client::QueryBody {
            variables,
            query: ping_query::QUERY,
            operation_name: ping_query::OPERATION_NAME,
        }
    }
}
```

I don't know about older compiler versions, but 1.37+ fail to compile this with:
```
error[E0428]: the name `ping_query` is defined multiple times
 --> src/queries/common.rs:2:1
  |
1 | pub struct ping_query;
  | ---------------------- previous definition of the type `ping_query` here
2 | pub mod ping_query {
  | ^^^^^^^^^^^^^^^^^^ `ping_query` redefined here
  |
  = note: `ping_query` must be defined only once in the type namespace of this module

error[E0428]: the name `ping_query` is defined multiple times
 --> src/queries/common.rs:2:1
  |
1 | pub struct ping_query;
  | ---------------------- previous definition of the type `ping_query` here
2 | pub mod ping_query {
  | ^^^^^^^^^^^^^^^^^^ `ping_query` redefined here
```

Apparently the module name and struct name are named the same.

And I found out why:
```rust
let module_name = Ident::new(&self.operation.name.to_snake_case(), Span::call_site());
let operation_name_ident = Ident::new(&self.operation.name, Span::call_site());
```
If the query is already in snake case, the above mentioned error happens.
Instead operation_name should be always converted to camel case like so:

```rust
let module_name = Ident::new(&self.operation.name.to_snake_case(), Span::call_site());
let operation_name_ident =
            Ident::new(&self.operation.name.to_camel_case(), Span::call_site());
```

Fixed in #253

**Comment by markcatley** [comment]
Hey, I encountered a very similar problem that I've documented in #254, and am about to open a PR with my fix that would also fix this issue.

While the solution you've proposed will work, it does so by through the use of non-idiomatic rust code. It is my understanding that structs should be in CamelCase, however, you've proposed a struct in snake_case.

My PR solves the problem by converting the query name into CamelCase before matching it with the struct name. To use it you would change the struct you derive on from `pub struct ping_query; to `pub struct PingQuery;`.

What do you think?

**Comment by davidgraeff** [comment]
> my understanding that structs should be in CamelCase

That's my understanding as well. Look closely at my proposed change, the structs name will be expected to be in camel case, exactly like with your solution.

To be honest I'm concentrating on cli generated code, so haven't thought about the derive case. Because a user should ideally get a decent error and proposed fix message which I'm not handling in my PR. 

In retrospective I also haven't thought about the case that the user has both names of queries, camel case and kebab case, defined in one file, ie: `ping_query` and `PingQuery`.
