### ISSUE TITLE
Union splays do not verify that matches are valid

### ISSUE THREAD

**Issue by mathstuf** [graphql-rust/graphql-client#275]
Given this schema:

```graphql
union SomeUnion = Int | String

type SomeNonUnionType {
    field: Int
}

type Query {
    someField: SomeUnion
}
```

This query has no diagnostics:

```graphql
query {
    someField {
        __typename
        ... on SomeNonUnionType {
            field
        }
    }
}
```

(Note that this is trimmed down by hand from my case from the GitHub schema; I'll test its actual behavior later today.)

Inside of a union query, any `on SomeType` should be verified to be a valid union type member. This probably also applies to interfaces.

**Comment by mathstuf** [comment]
Indeed. Using the latest release, this is still not warned about. Looking into making a PR.

**Comment by tomhoule** [comment]
In general it's a known issue that validation isn't complete. There are plans to extract the query validation from Juniper, long term. That would still be a valuable PR if you want to contribute this :)

**Comment by mathstuf** [comment]
On September 30, 2019 5:11:54 PM EDT, "Tom Houlé" <notifications@github.com> wrote:
>In general it's a known issue that validation isn't complete. There are
>plans to extract the query validation from Juniper, long term. That
>would still be a valuable PR if you want to contribute this :)

Already done :) . We found the error in production because GitHub rejected our queries. I'll add some tests to the PR when I get a chance.
