### ISSUE TITLE
CI seems to be broken

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#277]

**Comment by mathstuf** [comment]
Indeed. I noticed this when I was working on #276, however, I'm seeing a different error than CI (each toolchain actually seems to disagree on what's going wrong :/ ). I'm seeing:

```
thread 'tests::schema_with_keywords_works' panicked at 'Parse keywords schema: ParseError("Parse error at 7:1\nUnexpected `directive[Name]`\nExpected `scalar`, `type`, `interface`, `union`, `enum` or `input`\n")', src/libcore/result.rs:999:5
```

**Comment by mathstuf** [comment]
This can be closed now :) . See the above referenced PRs.

**Comment by tomhoule** [comment]
Indeed :) thanks!
