### ISSUE TITLE
normalize_query_types should not be a feature

### ISSUE THREAD

**Issue by mathstuf** [graphql-rust/graphql-client#283]
It being a feature means that anyone using it in the deptree changes the behavior for all projects in the tree. This is not valid use of features which must be additive, not transformative (`no_std` is an exception in this regard, but it is subtractive). Instead, the behavior should be toggled by an additional attribute parameter.

**Comment by mathstuf** [comment]
Cc: @markcatley

**Comment by tomhoule** [comment]
Indeed, I hadn't thought about it - let's fix it (tell me if you don't have the time and I'll take it in priority).
