### ISSUE TITLE
`derive(GraphQLQuery)` fails when query contains fragments which refer to other fragments

### ISSUE THREAD

**Issue by cairomassimo** [graphql-rust/graphql-client#286]
`derive(GraphQLQuery)` sometimes fails when the query contains a fragment which refers to a second fragment.
The error is due to the response struct for the innermost fragment not being generated, causing `error[E0412]: cannot find type <innermost fragment name> in this scope`.
This problem seems to happen only if the name of the innermost fragment is lexicographically smaller than the name of the containing fragment.

This is the smallest example illustrating the issue:

`src/schema.graphql`:

```graphql
type Query { x: String }
```

`src/query-good.graphql`:

```graphql
query Q { ...FragmentA }
fragment FragmentA on Query { ...FragmentB }
fragment FragmentB on Query { x }
```

`src/query-bad.graphql`:

```graphql
query Q { ...FragmentB }
fragment FragmentB on Query { ...FragmentA }
fragment FragmentA on Query { x }
```

`src/lib.rs`:
```rust
extern crate graphql_client;
extern crate serde;

use graphql_client::GraphQLQuery;

#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "src/schema.graphql",
    query_path = "src/query-bad.graphql"
)]
struct Q;
```

When running `cargo build`:
```
[...]
error[E0412]: cannot find type `FragmentA` in this scope
 --> src/lib.rs:6:10
  |
6 | #[derive(GraphQLQuery)]
  |          ^^^^^^^^^^^^ help: a struct with a similar name exists: `FragmentB`
[...]
```

Replacing `query-bad.graphql` with `query-good.graphql` it compiles successfully.

Version `0.8.0`.

**Comment by tomhoule** [comment]
Sorry for the late reply. That looks like a bad bug, I'll try to take a look at it asap (if someone else wants to it's more than welcome of course).

**Comment by mathstuf** [comment]
I wonder if the "used" tracking is missing a toggle somewhere.

**Comment by mathstuf** [comment]
I'm looking into it.

**Comment by cairomassimo** [comment]
Thanks for the quick fix! Keep up the good work :+1:

**Comment by Ten0** [comment]
I still have this issue on the current latest `graphql_client` (0.9) :(.

**Comment by tomhoule** [comment]
Please open a new issue so this can be tracked :pray:  Your comment will probably be forgotten if it's in a closed issue.

**Comment by mathstuf** [comment]
I probably should have added a test when I fixed this :/ .

**Comment by Ten0** [comment]
I beleive that is #291
