### ISSUE TITLE
Deserialization of mutation result yields wrong struct instance

### ISSUE THREAD

**Issue by morbatex** [graphql-rust/graphql-client#297]
Hi,
I've got the following mutation:

```
mutation InsertTransaction ($amount: Int!, $creditor: uuid!, $debitor: uuid!, $product: uuid!, $note: String ) {
  insert_transactions(objects: {amount: $amount, credit_id: $creditor, debit_id: $debitor, product_id: $product, note: $note}) {
    affected_rows
  }
}
```
Furthermore I use the following code to generate my structs:
 ```
#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "graphql/schema.graphql",
    query_path = "graphql/transaction.graphql",
)]
struct InsertTransaction;
```
If I send a request with a transaction to my server it answers with the following body:

```
"{\"data\":{\"insert_transactions\":{\"affected_rows\" : 1}}}"
```
but deserializing with serde leads to the following struct instance:

```
ResponseData {
    insert_transactions: None,
},
```
even as insert_transactions cleary is not `None`.

**Comment by tomhoule** [comment]
Hmm that looks like a bug. Can you share your schema? Or if you can't just the type of the `insert_transactions` field (for `affected_rows`).

**Comment by morbatex** [comment]
Sure, you can find the schema [here](https://github.com/graphql-rust/graphql-client/files/3992744/schema.txt)

**Comment by tomhoule** [comment]
Thanks! I will try to work on it asap but I can't guarantee I'll find the time. If someone else has time, feel free to investigate :)

**Comment by acelot** [comment]
@morbatex did you solve this problem? I came across the same problem, it feels like the `data` field is missing in generated models.

**Comment by morbatex** [comment]
@acelot I haven't found a real solution, but sidestepped the issue by not using the auto generated structs but defining them by hand.

**Comment by acelot** [comment]
@morbatex I found a workaround. I've just wrapped `ResponseData` into my own struct, so serde can properly deserialize the json. I've wrote universal graphql client:

```
use graphql_client::GraphQLQuery;
use reqwest::{Client, Error};
use serde::Deserialize;
use url::Url;

pub async fn request<Q: GraphQLQuery>(
    client: &Client,
    url: Url,
    variables: Q::Variables,
) -> Result<Data<Q::ResponseData>, Error> {
    let request = Q::build_query(variables);
    let response = client.post(url).json(&request).send().await?;
    let response_body = response.json::<Data<Q::ResponseData>>().await?;
    Ok(response_body)
}

#[derive(Deserialize)]
pub struct Data<D> {
    #[serde(rename = "data")]
    pub data: D,
}
```

**Comment by tomhoule** [comment]
Aah, if this is about the full response, there is the [`Response` struct](https://docs.rs/graphql_client/0.9.0/graphql_client/struct.Response.html) for this.

**Comment by acelot** [comment]
@tomhoule sprinkle ash on my head. Did not notice :)

**Comment by tomhoule** [comment]
Since it looks like this issue is solved, I think we can close :)
