### ISSUE TITLE
[Question] error[E0412]: cannot find type `DateTime` in module `super`

### ISSUE THREAD

**Issue by liangyuanpeng** [graphql-rust/graphql-client#303]
Hi guys, I have a problem with my github example

This is my query_1.graphql and my schema.graphql 

```
query RepoView($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
    homepageUrl
    stargazers {
      totalCount
    }
    pullRequests(first: 20, states: OPEN) {
      nodes {
        number
        closed
        createdAt
      }
    }
  }
}
```

```
pullRequest(
    "The number for the pull request to be returned."
    number: Int!

    closed: Boolean

    createdAt: DateTime

  ): PullRequest
```

But i just got some error when i run it
```
error[E0412]: cannot find type `DateTime` in module `super`
```

If i missed something, remind me please!

Thanks any help!!

**Comment by h-michael** [comment]
DateTime is not standard type. If you want use it, you should define custom type like this.
https://github.com/graphql-rust/graphql-client/blob/master/examples/github/examples/github.rs#L8

**Comment by liangyuanpeng** [comment]
@h-michael 
yes, you are right , thanks!

**Comment by Sleepful** [comment]
`type DateTime = String;` 👍
