### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by MarkMcCaskey** [graphql-rust/graphql-client#313]
Hello!  Thanks for making / maintaining this project!

I was looking at duplicate dependencies through `cargo tree -d` on a project using graphql-client recently and noticed that due to the syn and proc macro crates being < 1.0 on the latest released graphql-client-codegen, we seemingly have a lot of duplicated dependencies.

It seems like the update has already been done: https://github.com/graphql-rust/graphql-client/commit/1b3b120bf87971edcee3f463e24cac3e9519554a#diff-3662c16c0b0948c3da896eace0d0b8ce , it's just a matter of releasing it.

We'd appreciate an intermediate release of 0.9.0 before 1.0 if it's not too much trouble!

**Comment by tomhoule** [comment]
Thanks for the heads up - I just released 0.9.0 :)
