### ISSUE TITLE
Documentation: When are type aliases required?

### ISSUE THREAD

**Issue by cryslith** [graphql-rust/graphql-client#320]
For instance, the [github example](https://github.com/graphql-rust/graphql-client/blob/master/examples/github/examples/github.rs#L8) requires `type URI = String;` or else a rather cryptic error like

```
error[E0412]: cannot find type `URI` in module `super`
   |
   | #[derive(GraphQLQuery)]
   |          ^^^^^^^^^^^^ not found in `super`
   |
   = note: possible candidate is found in another module, you can import it into scope:
           crate::repo_view::URI
```

is raised at compile time.  It would be nice if the documentation mentioned this error message somewhere and explained how to solve it by defining an appropriate type alias.

**Comment by tomhoule** [comment]
Definitely!
