### ISSUE TITLE
Automatically implement Debug for generated Variables

### ISSUE THREAD

**Issue by colin-grapl** [graphql-rust/graphql-client#323]
It would be helpful to be able to debug print the Query and Variables that get generated by the macro. Currently these are not implemented, which means I have to manually implement them for the various types.

**Comment by tomhoule** [comment]
It's not very discoverable at the moment, but there is a `variables_derives = "Debug"` option you can put on the `graphql` attribute, like `response_derives`. I'm going to try to find some time to spend documenting and making things more discoverable soon.

**Comment by colin-grapl** [comment]
Aha, thank you, I wasn't able to find that.

**Comment by mathstuf** [comment]
Closing as resolved. Please reopen if needed.
