### ISSUE TITLE
GraphQL Client dependency fails to compile in workspace setting

### ISSUE THREAD

**Issue by jkelleyrtp** [graphql-rust/graphql-client#343]
<img width="1757" alt="image" src="https://user-images.githubusercontent.com/10237910/94708617-cedfcc00-0312-11eb-81c7-d966a6001623.png">

I'm not using the crate anywhere in my project, but simply having it in is enough to break compilation, which I assume is the fault of the derive crate. I've addressed this for myself in #342 but the issue seems to be larger than that.

**Comment by tomhoule** [comment]
The code has changed a lot on master. Please open a new issue if it happens again with 0.10.0 (to be released soon).
