### ISSUE TITLE
Issue with using external derive macro in `response_derives`

### ISSUE THREAD

**Issue by simonJasonK** [graphql-rust/graphql-client#348]
Hello. Thank you very much for your work on `graphql-client`. The crate has been a great help in allowing us to write type-safe code against our GraphQL queries. To further take advantage of this crate, we are trying to leverage [PyO3](https://github.com/PyO3/pyo3) to use `graphql-client` query responses in Python. Trying to use [dict-derive](https://github.com/gperinazzo/dict-derive)'s `IntoPyObject` derive macro to make the response compatible with the Python FFI yields an error. Please find the example below:

```
use dict_derive::IntoPyObject;
use graphql_client::*;

#[derive(graphql_client::GraphQLQuery)]
#[graphql(
    schema_path = "src/graphql/schema.graphql",
    query_path = "src/graphql/queries/foo.graphql",
    response_derives = "Serialize,IntoPyObject"
)]
struct Foo;
```

This code errors with:
```
error: cannot find derive macro `IntoPyObject` in this scope
 --> ffi/src/lib.rs:4:10
  |
4 | #[derive(graphql_client::GraphQLQuery)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

`foo::ResponseData` is a struct with one element `bar`, a `String`. Notably, the below code, which explicitly defines a struct `Foo` that I believe is equivalent to `foo::ResponseData`, compiles:

```
use dict_derive::IntoPyObject;

#[derive(IntoPyObject)]
struct Foo {
    bar: String
}
```

It seems to me that the `response_derives` option does not resolve the `dict_derive::IntoPyObject` import. Would anyone be kind enough to spend some time to help me figure out why?

We have workarounds to get our Python FFI working, but `response_derives` seems like the far more ergonomic option, if we can get it to work.

Thank you again for your time and work on `graphql-client`!

Platform:
```
macOS 10.14.4
cargo 1.48.0-nightly (9d1a4863a 2020-10-05)
```

Crate Versions:
```
graphql_client = "0.9.0"
dict_derive = "0.2.0"
```

**Comment by tomhoule** [comment]
Thanks for reporting this — it should be a matter of allowing extra imports into the generated modules. I do not remember whether we `use super::*`, but if so there would be a way to fix this with the current version (importing your trait in the parent module). Sadly I do not have time to work on graphql-client at the moment, but pull requests are welcome and will be reviewed :)

**Comment by simonJasonK** [comment]
@tomhoule, thanks a lot for the reply! Adding `use super::*` to the main code generation function fixed it. I have opened a pull request: https://github.com/graphql-rust/graphql-client/pull/349.

**Comment by tomhoule** [comment]
Closed by https://github.com/graphql-rust/graphql-client/pull/349 — thanks for the PR!
