### ISSUE TITLE
Error decoding response body in the github example

### ISSUE THREAD

**Issue by antislava** [graphql-rust/graphql-client#352]
Getting the following error when running the github example:

> Error: error decoding response body: expected value at line 2 column 1                                                                                        

Probably caused by the missing response body?
Note that the example works as expected at, for example, fc2a093f1837450a5448535682c3c48ae1fdd171 (Oct 30)

**Comment by siedentop** [comment]
Fixed in #351 . Will get merged very soon (I hope). 

In the meantime, here is how to the manual fix you can do yourself: https://github.com/graphql-rust/graphql-client/pull/351#issuecomment-730952905

(It just needs a `user_agent("bla/0.1")` set.)

**Comment by antislava** [comment]
Thanks, it works now!
