### ISSUE TITLE
Extend keyword?

### ISSUE THREAD

**Issue by lthiery** [graphql-rust/graphql-client#353]
I have a type such as:

```
type A {
    field_public: Int
}
```

Later on in the same file, I write:

```
extend type A {
   field_private: Int
}
```

It seems this does not get parsed though and the field_private for A is not generated for the code? Does the extend keyword not work?

**Comment by tomhoule** [comment]
It's indeed not implemented yet. There is an old issue about this.

**Comment by lthiery** [comment]
Sorry bout that - didn't come up on my search for 'extend' in Issues...

Anyway, thanks for confirming my suspicion. Feel free to close or leave open as a feature request.

**Comment by tomhoule** [comment]
Let's consider this a feature request :)
