### ISSUE TITLE
failure crate is officially deprecated

### ISSUE THREAD

**Issue by danielSanchezQ** [graphql-rust/graphql-client#360]
Hi!

I realize that `failure` crate is deprecated:

https://rustsec.org/advisories/RUSTSEC-2020-0036.html

I'm open to creating a PR migrating to some other library from the recommended ones.

The following are some suggested actively developed alternatives to switch to:

- anyhow
- eyre
- fehler
- snafu
- thiserror

**Comment by jszwedko** [comment]
I believe `failure` has already been removed in `master`. It just hasn't been released as a new version yet:

- graphql_client_codegen removed failure in code: https://github.com/graphql-rust/graphql-client/pull/308/files#diff-6c01d587ca0bb1030eef656c1e4ae571c7bf200a447c04870b968116306f526cL11-R11
- graphql_query_derive removed too: graphql-rust/graphql-client@9b3b685#diff-d62bd19f4ea738502debbe99d9baff29e9c5f7a3677d5eca2760c736d97e6c0cL14-R14

**Comment by mathstuf** [comment]
Looks to be right. Closing.

**Comment by phillipCouto** [comment]
When will a new version be released removing this dependency?

**Comment by Sytten** [comment]
@tomhoule Can you do the new version when you get the chance? Otherwise I would name a few code owners so we can ping them for those things.
