### ISSUE TITLE
Input Object arguments

### ISSUE THREAD

**Issue by ronanyeah** [graphql-rust/graphql-client#364]
Is something like this possible with this library?
https://atheros.ai/blog/input-object-type-as-an-argument-for-graphql-mutations-and-queries

I need the ergonomics of `issues_insert_input`, but with the ability to not pass certain fields:
https://github.com/graphql-rust/graphql-client/blob/master/examples/hasura/examples/query_1.graphql

**Comment by mathstuf** [comment]
I don't think I understand what you're asking for. What doesn't work with input objects today?

**Comment by ronanyeah** [comment]
I am autogenerating my schema and I think changing the output from that is the right way for me to solve this.
