### ISSUE TITLE
Error: error decoding response body

### ISSUE THREAD

**Issue by ajistrying** [graphql-rust/graphql-client#400]
command:
`graphql-client introspect-schema --output=hero_schema.json http://graph3.defikingdoms.com/subgraphs/name/defikingdoms/apiv5/graphql 
`

error:
`Something else happened. Status: 404
Error: error decoding response body: expected value at line 1 column 1
Location: /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1915:27`

I believe the response is returning something other than json, but I'm not exactly sure. Is there any way to check and/or is there a way to change the format so I can input it into the json file?

Thanks

**Comment by tomhoule** [comment]
https://github.com/graphql-rust/graphql-client/pull/385 should help there

**Comment by ajistrying** [comment]
perfect, this one can be closed down then, thank you! Is there a best practice for manually upgrading this client to bring in those changes?

**Comment by tomhoule** [comment]
I think you can `cargo install --git <URL>` in the meantime, but I'll try to find time to cut a crates.io release soon.

**Comment by tomhoule** [comment]
Thanks for the report, please don't hesitate to open a new issue if you still have problems.
