### ISSUE TITLE
Cannot compile queries without parameters

### ISSUE THREAD

**Issue by craftytrickster** [graphql-rust/graphql-client#402]
I am able to successfully compile examples that have variables such as

```graphql
query PuppySmiles($after: String) {
  reddit {
    subreddit(name: "puppysmiles") {
      newListings(limit: 6, after: $after) {
        title
        fullnameId
        url
      }
    }
  }
}
```

but if I try to use a query that does not have a variable (in this case, after)
```graphql
query FooBar {
  reddit {
    subreddit(name: "puppysmiles") {
      newListings(limit: 6, after: "foobar") {
        title
        fullnameId
        url
      }
    }
  }
}
```

The code does not compile for me.

**Comment by kinwolfqc** [comment]
Same problem, I cannot use any query that does not use variables(Which is most of them...)

**Comment by craftytrickster** [comment]
I just checked out this repo to fix this, and it seems like it actually already works in the repo. It seems that maybe they have not performed a cargo publish in a very long time (7 months), so perhaps it was fixed but never published.

**Comment by craftytrickster** [comment]
Either this was fixed, or this repo is abandonware, so closing
