### ISSUE TITLE
Using type ID in arguments seems to result in error

### ISSUE THREAD

**Issue by Sytten** [graphql-rust/graphql-client#405]
I was trying to replace my arguments that expect `ID` from `String` and it failed.

Example:
```graphql
query Scope($id: ID!) {
  scope(id: $id) {
    id
  }
}
```
Instead of:
```graphql
query Scope($id: ID!) {
  scope(id: $id) {
    id
  }
}
```

And it keeps failing with the error:
```rust
Response { 
  data: None,
  errors: Some([
    Error { 
      message: "Invalid value for argument \"id\", expected type \"ID\"",
      locations: Some([Location { line: 170, column: 9 }]),
      path: None, 
      extensions: None 
    }
  ])
}
```

Unsure why this happens?

**Comment by tomhoule** [comment]
I can't remember the implementation there, but couldn't it be because `ID` is a type alias / unit struct that is different from `String`?

**Comment by Sytten** [comment]
This is consequence of https://github.com/graphql-rust/graphql-client/issues/408
