### ISSUE TITLE
Any ideas how to get rid of `unused import` warnings?

### ISSUE THREAD

**Issue by bbigras** [graphql-rust/graphql-client#412]
Is it because I'm using `mod query`? (my generated file is `src/queries.rs`)

```
warning: unused import: `std::result::Result`
 --> src/queries.rs:4:9
  |
4 |     use std::result::Result;
  |         ^^^^^^^^^^^^^^^^^^^
```

**Comment by TieWay59** [comment]
This is fixed by https://github.com/graphql-rust/graphql-client/issues/414 & https://github.com/graphql-rust/graphql-client/pull/415

@bbigras @tomhoule

**Comment by tomhoule** [comment]
Thanks for reporting @TieWay59 , closing this issue then
