### ISSUE TITLE
Disable warnings and clippy for generated code

### ISSUE THREAD

**Issue by autarch** [graphql-rust/graphql-client#414]
The generated code causes a bunch of compiler warnings. It's probably possible to fix these, but the easiest path is just to add `#![allow(clippy::all)]` and `#![allow(warnings)]` at the top of the generated code. I can make a PR for this if this is something you want to do.

**Comment by autarch** [comment]
Also see #412

**Comment by tomhoule** [comment]
Yep, that sounds like a good idea, a PR would be great!
