### ISSUE TITLE
Any idea how to fix: cannot find type `JSON` in module `super`?

### ISSUE THREAD

**Issue by alexkingnz** [graphql-rust/graphql-client#418]
```
alex@replace:~/projects/shipit$ RUSTFLAGS="-Z macro-backtrace" cargo build
   Compiling shipit v0.1.0 (/home/alex/projects/shipit)
error[E0412]: cannot find type `JSON` in module `super`
  --> src/lib.rs:45:10
   |
45 | #[derive(GraphQLQuery)]
   |          ^^^^^^^^^^^^
   |          |
   |          not found in `super`
   |          in this derive macro expansion
   |
  ::: /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/graphql_query_derive-0.10.0/src/lib.rs:17:1
   |
17 | pub fn derive_graphql_query(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
   | -------------------------------------------------------------------------------------- in this expansion of `#[derive(GraphQLQuery)]`

For more information about this error, try `rustc --explain E0412`.
error: could not compile `shipit` due to previous error
```

**Comment by alexkingnz** [comment]
Any clues to where I should look next are welcome.

**Comment by alexkingnz** [comment]
I'm trying to use the monday.com api, querying against https://api.monday.com/v2.  My guess is something in the schema from there is causing a problem (since there are things named "JSON" there:
```
            {
              "args": [],
              "deprecationReason": null,
              "description": "Get the board communication value - typically meet
ing ID",
              "isDeprecated": false,
              "name": "communication",
              "type": {
                "kind": "SCALAR",
                "name": "JSON",
                "ofType": null
              }
            },
```

**Comment by alexkingnz** [comment]
So I have narrowed it down a bit more.  The following query compiles successfully:
`query GetBoard {boards (ids: 560201143) {columns { title id type} items { name column_values { id text }}}}`

This query fails to compile:
`query GetBoard {boards (ids: 560201143) {columns { title id type} items { name column_values { id value text }}}}`

Both of those queries execute successfully in Monday's developer playground web query tool.

So "value" in column_values is problematic.  Is this a case of a problematic Monday schema, or is it a problem of some kind of reserved or special 'JSON' identifier in graphql-client?

**Comment by Sytten** [comment]
Try to put `type JSON = String` in your file.

**Comment by LegNeato** [comment]
This is documented:

https://github.com/graphql-rust/graphql-client#custom-scalars

Please let us know if that doesn't fix it!
