### ISSUE TITLE
Autocomplete in VSCode for generated code?

### ISSUE THREAD

**Issue by nickwesselman** [graphql-rust/graphql-client#420]
I am a brand new baby Rustacean so perhaps I'm missing something, but generated code does not seem to be recognized in VSCode for syntax highlighting, autocomplete, etc. Any ideas on how to get this working?

**Comment by arjunyel** [comment]
Can you post an example? Are you using the rust-analyzer vs code extension?

**Comment by x10an14** [comment]
Here's an example of just that; I have no idea how to traverse the data structure further down.

Replace my hard-coded `org` and `project_num` gql variables with whatever project you'd like to test on (v1 - the old variant, not the new v2 ones that are now default).
https://git.sr.ht/~x10an14/github-project-migrator/tree/80c560d7bb031677ed400dd20243c2a8edc677be/item/src/main.rs

**Comment by nickwesselman** [comment]
Not sure what my issue was then but this totally works with rust-analyzer.
