### ISSUE TITLE
Community Maintenance

### ISSUE THREAD

**Issue by Sytten** [graphql-rust/graphql-client#426]
As expressed by the main developer @tomhoule, he doesn't have time to work on GraphQL-client anymore. This means the community needs to step up and take ownership of the project.

Please name yourself if you are interested in contributing to the project. We can also create a discord for better communication.

**Comment by tomhoule** [comment]
That can't happen without a transition phase. I can take time to review PRs occasionally, other people already have maintainer access to the repo and the  graphql-rust organization, so the project is not going to die. I am happy to add people who have made a few quality contributions to the maintainers.
