### ISSUE TITLE
CLI command for codegen

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#43]
It would be useful for people who want to generate the code in advance to get better editor support (RLS for example does not take into account generated code from derives yet).

Linking `proc_macro2` could be a challenge, from my past experience.

**Comment by h-michael** [comment]
@tomhoule 
I want this feature for code completion.
I think implementing code generation feature is possible by graphql_query_derive.
Do you have any ideas?

**Comment by tomhoule** [comment]
So in the current state, all the code generation logic lives in `graphql_query_derive` indeed. The idea would be to first refactor the top level functions in `lib.rs`, `schema.rs` and `query.rs` so we can expose a function like this:

```rust
pub fn generate_module(
  query: graphql_parser::query::Document,
  schema: graphql_query_derive::Schema,
  options: GraphQLClientDeriveOptions,
) -> TokenStream
```

The query is parsed directly from the `.graphql` file, the schema is parsed either from a `.graphql` or a `.json` file (there are `From` impls in `schema.rs`), and the options are currently extracted from the `#[graphql()]` attribute but they would have to be taken as CLI arguments.

The name `GraphQLClientDeriveOptions` is something I just came up with, we could find something better.

There are two caveats:

- I don't remember if it is possible to have other exports than the derive macros in a macro crate. If that is the case we would need to split codegen out of `graphql-query-derive` into a new `graphql-client-codegen` crate. This is not hard but it is work.

- Since we are working with `TokenStream`, I don't know if we can avoid dependency on the `proc-macro` crate, which is part of the compiler and cannot be statically linked. If we can't, this means the codegen part of the CLI will only work if you have the Rust compiler installed locally (and I am afraid of versioning problems there). This is an acceptable drawback however because presumably, if you are using `graphql-client`, you have a Rust compiler.

This is a refactoring we will need to do at some point because it enables other features (like using the codegen part of the library as a build script, if people are interested).

**Comment by h-michael** [comment]
@tomhoule 
> I don't remember if it is possible to have other exports than the derive macros in a macro crate. If that is the case we would need to split codegen out of graphql-query-derive into a new graphql-client-codegen crate. This is not hard but it is work.

We cannot other exports that has not `proc_macro_derive`.
So, I split codegen out of graphql-query-derive into a new graphql-client-codegen crate, first of all.

**Comment by tomhoule** [comment]
It sounds like the right thing to do. I just reserved the crate name on crates.io so you can use it.

**Comment by h-michael** [comment]
@tomhoule 
Now, I'm going to implement codegen command for cli.
But `graphql_client_codegen::codegen::response_for_query` needs not only schema and query but also additional_derives and deprecation_strategy.
How do you think it would be better to pass these two pieces of information?

**Comment by tomhoule** [comment]
I think ideally we have a `DeriveOptions` struct that is always the same. In the CLI it is controlled by passing flag arguments, and with the derive it uses the attributes on the structs. Is that what you mean?

**Comment by h-michael** [comment]
@tomhoule 
> Is that what you mean?
Thanks your reply, I understand.


We must meet this arguments.

```
pub fn response_for_query(
    schema: schema::Schema,
    query: query::Document,
    selected_operation: String,
    additional_derives: Option<String>,
    deprecation_strategy: deprecation::DeprecationStrategy,
)
```

Now, `selected_options, additional_derives, deprecation_strategy` are build from `DerivedInput`.

So I think `GraphQLClientDeriveOptions` needs to be expanded like this

```
pub struct GraphQLClientDeriveOptions<'a> {
    pub input: &'a syn::DeriveInput,
    selected_operation: &'a String,
    additional_derives: &'a Option<String>,
    deprecation_strategy: &'a deprecation::DeprecationStrategy,
}
```

or 

```
pub struct GraphQLClientDeriveOptions<'a> {
    selected_operation: &'a String,
    additional_derives: &'a Option<String>,
    deprecation_strategy: &'a deprecation::DeprecationStrategy,
}
```

**Comment by h-michael** [comment]
I think lower pattern is better.

**Comment by tomhoule** [comment]
Sorry for the late feedback. I like the second solution (that you implemented in your PR) better too.

**Comment by h-michael** [comment]
@tomhoule 
I think that I can close this already.

**Comment by tomhoule** [comment]
Absolutely, thanks again for working on that :)
