### ISSUE TITLE
skip_serializing_none does not work

### ISSUE THREAD

**Issue by Nohac** [graphql-rust/graphql-client#439]
I tried asking this question on the actual PR https://github.com/graphql-rust/graphql-client/pull/431 that was meant to solve this issue, but got no response, so I'm just gonna move the question into this issue.

I've added `skip_serializing_none` to the struct as stated in the README, but doing so still leaves me with `null` values after serialization.

My first guess was that this hasn't been released yet, so I switch over to the `main` branch in `Cargo.toml`, but that changed nothing. Here's the code I'm using:

```rust
#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "graphql/schema.graphql",
    query_path = "graphql/insert_mutation.graphql",
    response_derives = "Debug",
    skip_serializing_none
)]
pub struct InsertMutation;
```
```rust
let vars = Variables {
    // .. omitted
    user_id: None,
    // .. omitted
};

let q = crate::graphql::InsertMutation::build_query(vars);

let skipped = serde_json::to_string_pretty(&q).unwrap();
println!("{skipped}");
```
Output:
```json
{
  "variables": {
    // .. omitted
    "user_id": null,
    // .. omitted
  },
  ...
}
```

Is there something obvious I'm missing here to make this work, or is this something that warrants it's own issue?

**Comment by tomhoule** [comment]
I unfortunately don't have time to spend on this project to investigate further or fix things, but I'm happy to review PRs. FWIW it looks like a bug.

**Comment by Nohac** [comment]
Thanks for the quick reply.

This is unfortunately a blocking issue for me, unless there's some way to work around this issue. Since hasura 2.x now reports an error if input fields with null values are present, it's no longer possible to get the mutations to work.

I might try opening a PR if I get the time. Any hints on how approach fixing this issue would be appreciated.

**Comment by Nohac** [comment]
So I tried to switch to the git version again, and this time it seems to fix the problem, it's only v0.11.0 that doesn't work. So my first assumption was correct, that this features has not yet been released. Not sure why switching last time didn't work, might have been a caching issue or something.

Hoping we'll see a v.0.12.0 soon! Until then, I'm just gonna depend on the git repo directly.

**Comment by L1ghtman2k** [comment]
I am also running into this issue in v0.12.0, I think this issue should be reopened.

When expanding macro with skip_serialize_none, it doesn't seem like it is applied to the variables.

Example:

```
#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "./github.schema.graphql",
    query_path = "./github.query.graphql",
    response_derives = "Debug, PartialEq",
    skip_serialize_none
)]
pub struct BranchProtectionsView;
```
github.schema.graphql: https://docs.github.com/public/schema.docs.graphql

github.query.graphql:
```
query BranchProtectionsView($owner: String!, $name: String!, $cursor: String, $first: Int = 90) {
    repository(owner: $owner, name: $name) {
        branchProtectionRules(first: $first, after: $cursor) {
            pageInfo {
                endCursor
                hasNextPage
            }
            totalCount
            edges {
                cursor
                node {
                    pattern
                    requiresApprovingReviews
                }
            }
        }
    }
}
```

**Comment by Akremkadri** [comment]
I am encountering the same issue in v0.13.0. This problem should be reopened. When expanding a macro with skip_serialize_none, it appears that it is not being applied to the variables in the query.

**Comment by elimirks** [comment]
It seems like it only works for nested variables. Here's a test patch to reproduce:

```diff
diff --git a/graphql_client/tests/skip_serializing_none.rs b/graphql_client/tests/skip_serializing_none.rs
index 0d26184..40b0f9f 100644
--- a/graphql_client/tests/skip_serializing_none.rs
+++ b/graphql_client/tests/skip_serializing_none.rs
@@ -13,6 +13,7 @@ fn skip_serializing_none() {
     use skip_serializing_none_mutation::*;
 
     let query = SkipSerializingNoneMutation::build_query(Variables {
+        foo: None,
         param: Some(Param {
             data: Author {
                 name: "test".to_owned(),
@@ -26,4 +27,5 @@ fn skip_serializing_none() {
     println!("{}", stringified);
 
     assert!(stringified.contains(r#""data":{"name":"test"}"#));
+    assert!(stringified.contains(r#""variables":{"param":{"data":{"name":"test"}}}"#));
 }
diff --git a/graphql_client/tests/skip_serializing_none/query.graphql b/graphql_client/tests/skip_serializing_none/query.graphql
index 028ae76..f648300 100644
--- a/graphql_client/tests/skip_serializing_none/query.graphql
+++ b/graphql_client/tests/skip_serializing_none/query.graphql
@@ -1,4 +1,4 @@
-mutation SkipSerializingNoneMutation($param: Param) {
+mutation SkipSerializingNoneMutation($param: Param, $foo: Int) {
   optInput(query: $param) {
     name
     __typename
```

**Comment by elimirks** [comment]
@Akremkadri looks like you also ran into this issue recently, I submitted a PR here: https://github.com/graphql-rust/graphql-client/pull/485

Does it work for you?
