### ISSUE TITLE
Unable to get variables into graphql query?

### ISSUE THREAD

**Issue by iceaway** [graphql-rust/graphql-client#456]
Hello,

I am new to both Rust and grahpql and I'm trying to get a graphql-query with variables working. It appears that the issue is that my variable value is not getting injected into the graphql query. My very basic application looks like this:

```
use std::print;

use graphql_client::{reqwest::post_graphql_blocking as post_graphql, GraphQLQuery};
use ::reqwest::blocking::Client;
use log::*;

// The paths are relative to the directory where your `Cargo.toml` is located.
// Both json and the GraphQL schema language are supported as sources for the schema
#[derive(GraphQLQuery)]
#[graphql(
    schema_path = "graphql/schema.json",
    query_path = "graphql/price.graphql",
    response_derives = "Debug"
)]
pub struct PriceQuery;

fn main() {
    let house_id = "abced";
    let variables = price_query::Variables {
        house_id: house_id.to_string(),
    };
    let request_body = PriceQuery::build_query(variables);
    print!("{}", request_body.query);

    return;
}
```

This is my graphql-file:
```
query PriceQuery($house_id: String!) {
  viewer {
    home(id: $house_id) {
      currentSubscription{
        priceInfo{
          current{
            total
            energy
            tax
            level
            startsAt
          }
          today (time: $time) {
            total
            energy
            tax
            level
            startsAt
          }
          tomorrow {
            total
            energy
            tax
            level
            startsAt
          }
        }
      }
    }
  }
}
```
I was expecting that the graphql-query printed to the screen would show the actual value of `house_id` but it just prints everything exactly as in the graphql-file. Are my expectations wrong or am I doing something incorrectly? This should be quite trivial so it feels like I am missing something obvious.

**Comment by tomhoule** [comment]
Hi @iceaway! This is expected: the query that gets sent is verbatim the one you write, and the request contains that query, and the values for the variables in a separate object. There is [a GraphQL tutorial section](https://graphql.org/learn/queries/#arguments) on this. You can think of it like parameters of prepared statements in SQL.

**Comment by tomhoule** [comment]
If you (debug) print the whole `request_body` instead of `request_body.query` in your example, you should see the part where the variables are passed.

**Comment by iceaway** [comment]
Thanks for the tips! If I try to debug print (`println!("{:?})`) the `request_body` I get the error
```
the trait `std::fmt::Debug` is not implemented for `Variables`
```
Even though I have `response_derives = "Debug"` on my query. Do I need something more?

**Comment by tomhoule** [comment]
We should do a better job of documenting that, but there is a `variable_derives = "..."` option for the `Variables` struct.

**Comment by iceaway** [comment]
> We should do a better job of documenting that, but there is a `variable_derives = "..."` option for the `Variables` struct.

Fantastic, thank you! Now I can see my data in there. I had some issues where no data was returned from my graphql-query when I introduced variables so I thought it was due to the variable not being injected. But now I see that the error must be elsewhere.

**Comment by daviareias** [comment]
> We should do a better job of documenting that, but there is a `variable_derives = "..."` option for the `Variables` struct.

I realized I found about this feature before, but today I kept searching for its existence the entire day lol

**Comment by fmorency** [comment]
For posterity's sake, I used `variables_derives` (add an `s` to `variable`) and not `variable_derives`. The latter didn't work.
