### ISSUE TITLE
failed to parse schema

### ISSUE THREAD

**Issue by crazybits** [graphql-rust/graphql-client#482]
error is attached below, and the schema is downloaded with command `graphql-client introspect-schema https://api.mainnet.aptoslabs.com/v1/graphql  --output ./schema.graphql`

> #[derive(GraphQLQuery)]
   |          ^^^^^^^^^^^^
   |
   = help: message: called `Result::unwrap()` on an `Err` value: GeneralError("Parser error: schema parse error: Parse error at 1:1\nUnexpected `{[Punctuator]`\nExpected `schema`, `extend`, `scalar`, `type`, `interface`, `union`, `enum`, `input` or `directive`\n")

**Comment by tomhoule** [comment]
Could it be that your schema is JSON, but with a `.graphql` extension?
