### ISSUE TITLE
Support using the codegen part of the library as a build script?

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#63]
I want to gather feedback on the idea here. This would be an alternative to the custom derive. I see three potential advantages:

- More implicit codegen (no struct in user code, the modules are generated next to the queries)
- More consistent configuration
- Potential code sharing between queries (queries could share fragments, for example, but it might not be a good thing)

**Comment by tomhoule** [comment]
See [prost](https://github.com/danburkert/prost/) for an example of a library that does it right in my opinion.

**Comment by h-michael** [comment]
@tomhoule 
I think that I can close this already.

**Comment by mathstuf** [comment]
The CLI tool makes this possible. Closing since I think that's enough (though feel free to comment if that's not true).
