### ISSUE TITLE
Apply the visibility of the struct under derive to the generated module

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#77]
E.g. if the struct is private, so should be the module, if it's public, same thing, etc.

[syn::DeriveInput](https://docs.rs/syn/0.14.7/syn/struct.DeriveInput.html) exposes it quite conveniently

**Comment by davideGiovannini** [comment]
Hi @tomhoule,  I would like to work on this

**Comment by tomhoule** [comment]
Great :) I'm at work now but I'll try to add more details later.

**Comment by tomhoule** [comment]
Fixed by #177 (thanks @h-michael !)
