### ISSUE TITLE
CLI - how to integrate codegen properly?

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#78]
https://docs.rs/syn/0.14.7/syn/#optional-features

Edit: To make the issue less confusing, the problem is that we use types from the proc_macro2 crate (TokenStream...) to do codegen, and that can't be linked statically. So codegen from the CLI may be tricky.

**Comment by djc** [comment]
Not exactly sure what you're planning here, but just as an FYI: in my understanding you're not allowed to link to proc_macro from a binary running outside of the Rust compiler. See https://github.com/djc/askama/issues/73 and the linked issues for more information.

**Comment by tomhoule** [comment]
It was just a note because I remember having trouble in another project that did code generation using the proc macro infrastructure (syn, quote, etc.). I will put a disclaimer on the CLI README because it's not the highest priority feature at the moment (apollo-cli works just fine as a replacement).

**Comment by tomhoule** [comment]
Addressed by https://github.com/graphql-rust/graphql-client/pull/229 - also see the changelog.
