### ISSUE TITLE
Trim down prefixing of generated items

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-client#80]
We don't need the `Rust` prefix, probably

**Comment by LegNeato** [comment]
Should we do no prefix by default and let the user configure it?

**Comment by tomhoule** [comment]
That's the safest option probably, although  I don't see a use-case for prefixing happening often anymore, since, if my memory is right, we already prefix the generated items with the query name, in addition to wrapping everything in a module. For example:

```graphql
query People {
  person(id: 1) { name }
}
```

Will generate a struct called `RustPeoplePerson`. Fragments are also their own "roots". So collisions can happen but should be rare, so we could probably do custom prefixing, defaulting to nothing.

Example query that should collide with the generated `ResponseData` without prefixing, for testing purposes:

```graphql
query Response {
  data
}
```

**Comment by tomhoule** [comment]
Hmm, sorry for reacting to your last comment that late. Since a given ResponseData's fields are specific to one query, I don't think there is a way around generating it. I am not sure I understand entirely.
